### ISSUE TITLE
Software Updates

### ISSUE THREAD

**Issue by meminyanik** [DevSidus/Sidus_Github#31]
1- accWorld ve accWorldEstimated değerleri m/s^2 olarak sabitlenecek (GS'ye göndermek de dahil). accelDiff m/s^3 olacak.
2- accel verisi accelRow olabilir.
3- accX, accY, AccAlt değişkenleri kavramları netleştirilecek
4- qc.accelDiff.x = filtObjAccelDiffX.filter(qc.accelWorld.x, deltaTimeAccelDiff);  ProcessPID icinden kaldırılacak
5- atan(pidVars.accY.output / PID_ACC_Y_OUTMAX) * 180 / M_PI; kısmı açısal olarak hesaplanıp sonra limitlenecek
6- GS'de Acc PID katsayilari Pos ve Alt olarak iki secenek halinde sunulabilecek

**Comment by agcaahmet** [comment]
This issue can be closed with the latest commits.

**Comment by meminyanik** [comment]
Eyvallah Ahmedim eline saglik. Good job man:)
